### ISSUE TITLE
Demo Tutorial Blog?

### ISSUE THREAD

**Issue by soltrinox** [RasaHQ/retail-demo#2]
Is there a tutorial blob article for this yet?

**Comment by desmarchris** [comment]
@soltrinox nothing yet :) I'm currently developing the bot itself then will add more and publish when it's finished

**Comment by desmarchris** [comment]
@soltrinox we have a blog up now but it's more of an intro to the start pack: https://blog.rasa.com/new-rasa-starter-pack-retail/

I also added a readme to get it started. Let me know if you still have questions on how it works so I can improve the docs!
