### ISSUE TITLE
README overview of files not consistent with the directory

### ISSUE THREAD

**Issue by Sirneij** [RasaHQ/retail-demo#25]
This part of README:
## Overview of the files

`data/core.md` - contains stories

`data/nlu.md` - contains NLU training data

`actions.py` - contains custom action/api code

`domain.yml` - the domain file, including bot response templates

`config.yml` - training configurations for the NLU pipeline and policy ensemble

`tests/test_stories.yml` - end-to-end test stories

is not consistent with what is seen in the directories. No `core.md` particularly.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @samsucik will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by samsucik** [comment]
Hey @Sirneij, you're right, I think the overview part was maybe copy-pasted 🤔  Would you be up for fixing it and creating a pull request with the changes?

**Comment by Sirneij** [comment]
@samsucik, I should only change the README.md file? If yes, no p

**Comment by Sirneij** [comment]
@samsucik I should only change the README.md file? If yes, no probs.

**Comment by samsucik** [comment]
@Sirneij yeah, I don't see anything else to be touched in order for this issue to be closed 🙂

**Comment by Sirneij** [comment]
@samsucik I'll do just that ASAP 😎

**Comment by Sirneij** [comment]
Fixed
