### ISSUE TITLE
data/rules.yml

### ISSUE THREAD

**Issue by joggerjoel** [RasaHQ/retail-demo#29]
How to fix this issue?

UserWarning: Issue found in 'data/rules.yml':
Found an unexpected step in the rule description:
{'entities': ['negation']}
It will be skipped.

```
rasa --version
Rasa Version      :         2.5.0
Minimum Compatible Version: 2.2.0a1
Rasa SDK Version  :         2.5.0
Rasa X Version    :         None
Python Version    :         3.8.5
Operating System  :         Linux-5.8.0-50-generic-x86_64-with-glibc2.29
Python Path       :         /usr/bin/python3
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by hsm207** [comment]
@joggerjoel there was a typo in the way we wrote the rule. thanks for highlighting this. It's already fixed in the main branch
