### ISSUE TITLE
Update the license for the repo

### ISSUE THREAD

**Issue by seagate2014** [RasaHQ/retail-demo#31]
Please update the license for the repo.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @b-quachtran will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by abhijitnargund** [comment]
As per RASA docs :

**Comment by seagate2014** [comment]
Hey @b-quachtran ,
RASA docs state that all starter kits are open source.
When can we expect an update on this ?

**Comment by b-quachtran** [comment]
@seagate2014 Just added 😄

**Comment by seagate2014** [comment]
Thank you..Really appreciate the great work RASA team is doing..
