### ISSUE TITLE
fix requirements.txt

### ISSUE THREAD

**Issue by JleenDeniel** [RasaHQ/retail-demo#36]
I have some problems with requirements.txt, got mistaces like ''' The conflict is caused by:
    The user requested tensorflow-addons==0.14
    rasa 3 0 0 depends on tensorflow-addons<=* and >=* '''
I dont think that its right to fix every line of requirements by my self

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Tanya-11** [comment]
Hi @sara-tagger, @akelad
any update on this?

**Comment by aldesfi** [comment]
up

**Comment by smitesh-sutaria** [comment]
@aldesfi , @sara-tagger @JleenDeniel @akelad
Have a look at the below PR : 
 https://github.com/RasaHQ/retail-demo/pull/39
