### ISSUE TITLE
Rename "DucklingHTTPExtractor" to "DucklingEntityExtractor"

### ISSUE THREAD

**Issue by SCNUJackyChen** [RasaHQ/retail-demo#37]
I think the "DucklingHTTPExtractor" has been renamed to "DucklingEntityExtractor" according to [here](https://github.com/RasaHQ/rasa/issues/5661). So the `config.yml` file may need to update.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by JustinaPetr** [comment]
Hey @SCNUJackyChen. The component is referenced as `DucklingEntityExtractor` in the pipeline. Could you point me to the part of the docs where you see the old naming being used just in case we missed updating it somewhere?

**Comment by SCNUJackyChen** [comment]
> Hey @SCNUJackyChen. The component is referenced as `DucklingEntityExtractor` in the pipeline. Could you point me to the part of the docs where you see the old naming being used just in case we missed updating it somewhere?

Hi @JustinaPetr . You may check [here](https://github.com/RasaHQ/retail-demo/blob/a95787c41ae98c9ab8ca4734fc5f12ad5a166aad/config.yml#L30).
