### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by Banukakdu** [RasaHQ/retail-demo#38]
please check the requirement.txt it gives multiple issues while installing dependencies

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by phamhunglam** [comment]
change version:
rasa==2.3.1
rasa-sdk==2.3.1

**Comment by aldesfi** [comment]
pip install -r requirements.txt fo hundred times 😅😂

**Comment by smitesh-sutaria** [comment]
@sara-tagger @Banukakdu  @akelad @dakshvar22 
Have a look at the below PR : 
 https://github.com/RasaHQ/retail-demo/pull/39
